reporter:
  image:
    pullPolicy: Never
    repository: hbf-reporter-crud
    tag: latest
  logLevel: DEBUG
  logType: pretty
  ports:
    addressPort: 9000
    addressPortAlias: reporter
  postgres:
    host: 172.25.143.81
    port: 5432
    name: postgres
    user: nkiver
    pwd: nkiver
    schema: report
  restartPolicy: OnFailure

service:
  port: 9000
  type: LoadBalancer

stage: dev
ingressName: 172.25.143.81
ingressPort: 9000

defaults:
  securityContext: {}