imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 9001
    protocol: TCP

service:
  ports:
    - port: 80
      name: http
      targetPort: 9001


ingress:
  enabled: true
  objects:
    - servicePort: 80
      annotations:
        # nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
      - name: "{{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}"
        path: /hbf

env:
  APP_PORT: "9001"
  INGRESS_NAME: "{{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}"
  INGRESS_PORT: "80"
  INGRESS_PATH: hbf
  API_VERSION: v1
  DB_USER: user_admin
