apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-hbf-reporter-crud
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        component: {{ .Release.Name }}-hbf-reporter-crud
    ports:
        - port: {{ .Values.service.port }}
          targetPort: {{ .Values.reporter.ports.addressPort }}
    type: {{ .Values.service.type }}