vault:
  enabled: true
  env:
    - services/testops/prd/testops-pgsql-cl1/user_admin:
        DB_PASSWORD: password

  entrypoint: "sh /app/entrypoint.sh"

env:
  LOG_LVL: "DEBUG"
  LOG_TYPE: "pretty"
  STAGE: prod
  TRUSTED_ADDRESS: http://frontops-ingress-controller.frontops.svc.k8s.prod-dl
  DB_NAME: testops

config:
  path: /app
  files:
    entrypoint.sh:
      data: |-
        #!/bin/bash
        DB_URL=testops-pgsql-cl1-haproxy.testops.svc.k8s.prod-dl:5000
        DB_USER=$DB_USER
        DB_PASSWORD=$DB_PASSWORD
        DB_URL=$DB_URL
        DB_NAME=$DB_NAME

        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_URL}/${DB_NAME}?schema=func_report&application_name=hbf-report-crud"
        export DATABASE_URL=$DATABASE_URL
        exec node ./build/index.js
